// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgxV5cVYS2cVO6yFQ9CyE5ogOSdhvhao',
    appId: '1:756748659767:web:aecd21659fa6dba497e3b2',
    messagingSenderId: '756748659767',
    projectId: 'medisafe-55098',
    authDomain: 'medisafe-55098.firebaseapp.com',
    storageBucket: 'medisafe-55098.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQOVMmecJ6NvfKnxtyFOsC2nUa9XzHQM',
    appId: '1:756748659767:android:fd4506230ff1ad8a97e3b2',
    messagingSenderId: '756748659767',
    projectId: 'medisafe-55098',
    storageBucket: 'medisafe-55098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YwdYqz1mIxiq4q_EOKgfw6U608ZDIRM',
    appId: '1:756748659767:ios:44820db31bc54c0497e3b2',
    messagingSenderId: '756748659767',
    projectId: 'medisafe-55098',
    storageBucket: 'medisafe-55098.firebasestorage.app',
    iosBundleId: 'com.example.medisafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4YwdYqz1mIxiq4q_EOKgfw6U608ZDIRM',
    appId: '1:756748659767:ios:44820db31bc54c0497e3b2',
    messagingSenderId: '756748659767',
    projectId: 'medisafe-55098',
    storageBucket: 'medisafe-55098.firebasestorage.app',
    iosBundleId: 'com.example.medisafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxgxV5cVYS2cVO6yFQ9CyE5ogOSdhvhao',
    appId: '1:756748659767:web:684291872ecfd65897e3b2',
    messagingSenderId: '756748659767',
    projectId: 'medisafe-55098',
    authDomain: 'medisafe-55098.firebaseapp.com',
    storageBucket: 'medisafe-55098.firebasestorage.app',
  );
}
